services:
  # Este es nuestro servicio de backend
  - type: web
    name: mi-lector-ia-backend
    # ¡IMPORTANTE! Le decimos a Render que use Docker
    env: docker
    # Ubicación del Dockerfile
    dockerfilePath: ./backend/Dockerfile
    # Plan gratuito
    plan: free
    # Región que ya estabas usando
    region: frankfurt
    # Variables de entorno que NO son secretas
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: FRONTEND_URL
        # Asegúrate de que esta URL es la correcta para tu GitHub Pages
        value: https://batjuancrespo.github.io/lector-ia-web/